### Создать взрослого мужчину
POST http://localhost:8080/family-service/person
Content-Type: application/json

{
  "category": "ADULT",
  "firstName": "Ivan",
  "lastName": "Ivanov",
  "birthDate": "1995-02-02",
  "gender": "MALE",
  "address": "Minsk",
  "monthlyIncome": 1000.0,
  "job": "IT Company"
}

### Создать персону неудачно
POST http://localhost:8080/family-service/person
Content-Type: application/json

{
  "category": "ADULT",
  "firstName": null,
  "lastName": "Ivanov",
  "birthDate": "1995-02-02",
  "gender": "MALE",
  "address": "Minsk",
  "monthlyIncome": 1000.0,
  "job": "IT Company"
}

### Создать взрослого мужчину
POST http://localhost:8080/family-service/person
Content-Type: application/json

{
  "category": "ADULT",
  "firstName": "Petr",
  "lastName": "Petrov",
  "birthDate": "1995-02-02",
  "gender": "MALE",
  "address": "Minsk",
  "monthlyIncome": 0
}

### Создать взрослую женщину
POST http://localhost:8080/family-service/person
Content-Type: application/json

{
  "category": "ADULT",
  "firstName": "Anna",
  "lastName": "Ivanova",
  "birthDate": "1995-02-02",
  "gender": "FEMALE",
  "address": "Minsk",
  "monthlyIncome": 1000.0,
  "job": "IT Company"
}

### Создать ребенка. Id здесь и дальше заполнены, но при самостоятельном запуске
### требуется подстановка исходя из выполнения предыдущих запросов
POST http://localhost:8080/family-service/person
Content-Type: application/json

{
  "category": "CHILD",
  "firstName": "Semen",
  "lastName": "Ivanov",
  "birthDate": "2002-02-02",
  "gender": "MALE",
  "address": "Minsk",
  "motherId": "0bc6c91c-3402-4008-ba9d-903c7dbc27fb",
  "fatherId": "25d67431-add5-4464-84ac-fb46c7b9605e"
}

### Создать ребенка
POST http://localhost:8080/family-service/person
Content-Type: application/json

{
  "category": "CHILD",
  "firstName": "Maria",
  "lastName": "Petrova",
  "birthDate": "2023-02-02",
  "gender": "FEMALE",
  "address": "Minsk",
  "motherId": "0bc6c91c-3402-4008-ba9d-903c7dbc27fb",
  "fatherId": "f9173439-53ce-46b9-a318-bb4f7b9bc46b"
}

### Обновить взрослого
PUT http://localhost:8080/family-service/person
Content-Type: application/json

{
  "id": "25d67431-add5-4464-84ac-fb46c7b9605e",
  "firstName": "Ivan",
  "lastName": "Ivanov",
  "address": "Erevan",
  "monthlyIncome": 100000.0,
  "job": "IT Company"
}

### Обновить неудачно
PUT http://localhost:8080/family-service/person
Content-Type: application/json

{
  "id": "7417fd7f-af87-4f51-ae32-4d278a0aecfb",
  "firstName": "Ivan",
  "lastName": "Ivanov",
  "address": "Minsk",
  "monthlyIncome": 1000.0,
  "job": "IT Company"
}

### Получить семью по матери
GET http://localhost:8080/family-service/family?personId=0bc6c91c-3402-4008-ba9d-903c7dbc27fb

### Получить семью по отцу
GET http://localhost:8080/family-service/family?personId=25d67431-add5-4464-84ac-fb46c7b9605e

### Получить семью по ребенку
GET http://localhost:8080/family-service/family?personId=c271d670-064c-4f3b-8b94-92779b924c8c

### Получить всех
GET http://localhost:8080/family-service/person/all

### Получить всех взрослых
GET http://localhost:8080/family-service/person/all?category=ADULT

### Получить всех детей
GET http://localhost:8080/family-service/person/all?category=CHILD

### Получить по id
GET http://localhost:8080/family-service/person?id=25d67431-add5-4464-84ac-fb46c7b9605e

### Получить по несуществующему id
GET http://localhost:8080/family-service/person?id=00000000-0000-0000-0000-000000000000





